export enum Source {
  TabNews = "TabNews",
  HackerNews = "HackerNews",
}

export enum CacheKey {
  TabNews = "tabnews",
  HackerNews = "hackernews",
  TabNewsComments = "comments",
  Highlights = "highlights",
}

export interface Comment {
  id: string;
  parent_id: string | null;
  owner_username: string;
  body: string;
  created_at: string;
  children: Comment[];
  tabcoins?: number;
}

export interface NewsItem {
  id: string;
  title: string;
  author: string;
  score: number;
  publishedAt: string; // ISO String
  source: Source;
  url?: string; // External URL for HN
  sourceUrl?: string | null; // External URL for TabNews (if link post)
  slug?: string; // TabNews slug
  owner_username?: string; // TabNews owner
  body?: string; // Markdown content
  commentCount?: number;
}

export type ViewMode = "mix" | "tabnews" | "hackernews";

// API Response types (Simplified)
export interface TabNewsItem {
  id: string;
  owner_username: string;
  slug: string;
  title: string;
  body?: string;
  published_at: string;
  tabcoins: number;
  children_deep_count: number;
  source_url?: string | null;
}

// Official Firebase API Type
export interface HackerNewsItem {
  id: number;
  title: string;
  score: number;
  by: string;
  time: number; // Unix timestamp in seconds
  url?: string;
  descendants?: number; // comment count
  type: string;
}

// Cache interface
export interface CacheEntry<T> {
  data: T;
  timestamp: number;
}

// Service Status Types
export enum ServiceStatusType {
  Operational = "operational",
  Degraded = "degraded",
  Down = "down",
}

export interface ServiceStatus {
  name: string;
  status: ServiceStatusType;
  lastChecked: string; // ISO 8601
  url: string; // Link para a página de status oficial
}

export interface ServicesStatusResponse {
  services: ServiceStatus[];
  lastUpdate: string; // ISO 8601
}

// Highlights Types
export type HighlightSource = "twitter" | "reddit";

export interface HighlightEngagement {
  likes?: number; // Twitter
  comments: number; // Both
  shares?: number; // Twitter (retweets)
  upvotes?: number; // Reddit
}

export interface Highlight {
  id: string;
  title: string; // Title extracted or generated by AI
  summary: string; // 1-2 line summary made by AI
  source: HighlightSource;
  author: string; // username without @
  url: string; // Link to original post/thread
  engagement: HighlightEngagement;
  publishedAt: string; // ISO timestamp
  aiConfidence: number; // 0-100 (how relevant AI considers it)
  aiSummary?: string; // Resumo IA Gemini (opcional)
}

// Reddit API Response Types
export interface RedditPost {
  data: {
    id: string;
    title: string;
    author: string;
    selftext: string;
    url: string;
    permalink: string;
    score: number; // upvotes - downvotes
    ups: number; // upvotes
    num_comments: number;
    created_utc: number; // Unix timestamp
    subreddit: string;
    is_self: boolean; // true if text post
    over_18: boolean;
  };
}

export interface RedditResponse {
  data: {
    children: RedditPost[];
    after?: string;
    before?: string;
  };
}
