export enum Source {
  TabNews = "TabNews",
  HackerNews = "HackerNews",
}

export enum CacheKey {
  TabNews = "tabnews",
  HackerNews = "hackernews",
  TabNewsComments = "comments",
  Highlights = "highlights",
  SmartMix = "smartmix",
}

export interface Comment {
  id: string;
  parent_id: string | null;
  owner_username: string;
  body: string;
  created_at: string;
  children: Comment[];
  tabcoins?: number;
}

export interface NewsItem {
  id: string;
  title: string;
  author: string;
  score: number;
  publishedAt: string; // ISO String
  source: Source;
  url?: string; // External URL for HN
  sourceUrl?: string | null; // External URL for TabNews (if link post)
  slug?: string; // TabNews slug
  owner_username?: string; // TabNews owner
  body?: string; // Markdown content
  commentCount?: number;
  techScore?: number; // AI-based tech relevance score (0-100)
}

export type ViewMode = "mix" | "tabnews" | "hackernews";

// API Response types (Simplified)
export interface TabNewsItem {
  id: string;
  owner_username: string;
  slug: string;
  title: string;
  body?: string;
  published_at: string;
  tabcoins: number;
  children_deep_count: number;
  source_url?: string | null;
}

// Official Firebase API Type
export interface HackerNewsItem {
  id: number;
  title: string;
  score: number;
  by: string;
  time: number; // Unix timestamp in seconds
  url?: string;
  descendants?: number; // comment count
  type: string;
}

// Cache interface
export interface CacheEntry<T> {
  data: T;
  timestamp: number;
}

// Service Status Types
export enum ServiceStatusType {
  Operational = "operational",
  Degraded = "degraded",
  Down = "down",
}

export interface ServiceStatus {
  name: string;
  status: ServiceStatusType;
  lastChecked: string; // ISO 8601
  url: string; // Link para a página de status oficial
}

export interface ServicesStatusResponse {
  services: ServiceStatus[];
  lastUpdate: string; // ISO 8601
}

// Highlights Types
export type HighlightSource = "twitter" | "reddit" | "devto";

export interface HighlightEngagement {
  likes?: number; // Twitter
  comments: number; // Both
  shares?: number; // Twitter (retweets)
  upvotes?: number; // Reddit
}

export interface Highlight {
  id: string;
  title: string; // Title extracted or generated by AI
  summary: string; // 1-2 line summary made by AI
  source: HighlightSource;
  author: string; // username without @
  url: string; // Link to original post/thread
  engagement: HighlightEngagement;
  publishedAt: string; // ISO timestamp
  aiConfidence: number; // 0-100 (how relevant AI considers it)
  aiSummary?: string; // Resumo IA Gemini (opcional)
}

// Reddit API Response Types
export interface RedditPost {
  data: {
    id: string;
    title: string;
    author: string;
    selftext: string;
    url: string;
    permalink: string;
    score: number; // upvotes - downvotes
    ups: number; // upvotes
    num_comments: number;
    created_utc: number; // Unix timestamp
    subreddit: string;
    is_self: boolean; // true if text post
    over_18: boolean;
  };
}

export interface RedditResponse {
  data: {
    children: RedditPost[];
    after?: string;
    before?: string;
  };
}

// Twitter/X API Response Types
export interface TwitterTweet {
  id: string;
  text: string;
  author_id: string;
  created_at: string; // ISO 8601
  public_metrics: {
    retweet_count: number;
    reply_count: number;
    like_count: number;
    quote_count: number;
    bookmark_count: number;
    impression_count: number;
  };
  entities?: {
    urls?: Array<{
      url: string;
      expanded_url: string;
      display_url: string;
    }>;
    hashtags?: Array<{
      start: number;
      end: number;
      tag: string;
    }>;
  };
  referenced_tweets?: Array<{
    type: "retweeted" | "quoted" | "replied_to";
    id: string;
  }>;
}

export interface TwitterUser {
  id: string;
  name: string;
  username: string;
  verified?: boolean;
  public_metrics?: {
    followers_count: number;
    following_count: number;
    tweet_count: number;
  };
}

export interface TweetWithAuthor {
  tweet: TwitterTweet;
  username: string;
}

// Dev.to API Response Types
export interface DevToArticle {
  id: number;
  title: string;
  description: string;
  published_at: string; // ISO 8601
  tag_list: string[];
  slug: string;
  url: string;
  canonical_url: string;
  comments_count: number;
  public_reactions_count: number;
  positive_reactions_count: number;
  user: {
    name: string;
    username: string;
    twitter_username?: string;
    github_username?: string;
  };
  organization?: {
    name: string;
    username: string;
    slug: string;
  };
  reading_time_minutes: number;
}

export interface ArticleWithAuthor {
  article: DevToArticle;
  username: string;
}

// Union type com discriminator 'type' para feed unificado
export type FeedItem =
  | ({ type: "news" } & NewsItem)
  | ({ type: "highlight" } & Highlight);

// Response do endpoint /api/feed
export interface FeedResponse {
  items: FeedItem[];
  nextCursor: string | null;
}
